apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: basic-cluster
  region: eu-west-2
  version: "1.21"

nodeGroups:
  - name: ng1-public
    instanceType: t2.medium
    desiredCapacity: 4